<?php
require_once('../includes/header.php');
require_once('../includes/head.php');
require_once('../mysql/conexion.php');
require_once('ingresar/modal_ingresar.php');
require_once('contenido.php');
require_once('../includes/footer.php');
require_once('ingresar/funciones.php');
?>